name: conditional checks
on: workflow_dispatch
jobs: 
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: failing-test
      run: kouuoijn
    - name: i will not run
      run: echo ${{ fromjson(github) }}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: failure()
    steps:
    - name: clear
      run: echo "clearing the workspace"
      
    
