name: conditional checks
on: workflow_dispatch
jobs: 
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: failing-test
      continue-on-error: true
      run: kouuoijn
    - name: i will not run
      run: echo ${{ github }}|jq

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: always()
    steps:
    - name: clear
      run: echo "clearing the workspace"
      
    
