name: Docker Image CI
env:
  IMAGE_TAG: "latest"
on:
  issues:
    # this is filter. Activity Types for the mentioned event
    types: [ "opened", "deleted" ]
  push:
    branches: [ "main" ]
    paths-ignore:
      - ".github/workflows/*"
  workflow_dispatch:
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: |
        echo "${{ github.sha }} triggered this workflow."
        cd ./api && docker build . --file Dockerfile --tag my-image-name:${{ env.IMAGE_TAG }}
