name: Docker Image CI
env:
  IMAGE_TAG: "latest"
on:
  issues:
    # this is filter. Activity Types for the mentioned event
    types: [ "opened", "deleted" ]
  push:
    branches: [ "main" ]
    paths-ignore:
      - ".github/workflows/*"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      IMAGE: ${{ steps.buildimage.outputs.IMAGE_TAG }}
    steps:
    - name: Get code
      uses: actions/checkout@v4
    
    - name: Build the Docker image
      id: buildimage
      run: |
        echo "${{ github.sha }} triggered this workflow."
        echo "IMAGE_TAG=${{ env.IMAGE_TAG }}" >> $GITHUB_OUTPUT
        cd ./api && docker buildx . --file Dockerfile --output=/tmp/newimage --tag my-image-name:${{ env.IMAGE_TAG }}
    - name: cache the build artifacts
      uses: actions/cache@v4
      with: 
        path: |
          /tmp/newimage
  publish:
    runs-on: ubuntu-latest
    needs: build
    env: 
        output1: ${{ needs.build.outputs.IMAGE }}
    steps:
    - name: print output 
      run: echo "$output1"
