name: matrix-workflow
on: 
  workflow_dispatch

jobs:
  job1:
    strategy:
      matrix:
        os: ["ubuntu-latest","windows-latest"]
        parameter: ["hello","tello"]
        exclude:
        - os: "ubuntu-latest"
        - parameter: "tello"
    runs-on: ${{ matrix.os }}
    steps:
    - name: print
      if: ${{ matrix.os == 'windows-latest' }}
      run: echo %${{ matrix.parameter }}%
    - name: print-unix
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: echo ${{ matrix.parameter }}
      
